export enum PATH {
  ALL = "*",
  HOME = "/",
  DASHBOARD = "/AdminDashboard",
  SKUDESIGN = "/SKUDesign",
  TRACKING = "/Tracking",
  PRODUCT= "/Product",
  FULFILLMENT= "/Fulfillment",
  PAGE2D= "/Page2D",
  LOGIN = "/Login",
  // FORGOT_PASSWORD = "/forgot-password",
  FORGOT_PASSWORD = "/ForgotPassword",
  RESET_PASSWORD = "/reset-password",
  PROFILE = "/profile",
  USERS = "/User",
  ADMIN_ROLES = "/admin-roles",
  ADMIN_USERS = "/admin-users",
  DATAELEMENT = "/dataement",
  DATASET = "/dataset",
  FORM = "/form",
  FORM_INSTANCE = "/form-instance",
  ORGUNIT = "/orgunit",
  PERIOD = "/period",
  PERSON = "/person",
  PROGRAM = "/program",
}
